---
- name: Update and upgrade apt packages
  apt:
    upgrade:            dist
    update_cache:       yes
    autoremove:         yes
    force_apt_get:      yes
  register:             upgrade_results
  become:               true
  
- name: check reboot required file
  stat:
    path:               "/var/run/reboot-required"
  register:             reboot_required_file
  
- name: ensure that config.txt cmdline is correct
  lineinfile:
    path:               "/boot/firmware/config.txt"
    regexp:             '^cmdline='
    line:               "cmdline=cmdline.txt"
  register:             boot_config
  become:               true
  
- name: Install needed tools
  apt: 
    name:             "{{ packages }}"
    state:            present
    update_cache:     yes
    autoremove:       yes
    force_apt_get:    yes
  vars:
    packages:
    - rpi-eeprom
    - sshpass
  become:             true
  
- name: Check if firmware update is needed
  shell:              "rpi-eeprom-update"
  register:           firmware_check_cmd
  failed_when:        firmware_check_cmd.rc != 0 and firmware_check_cmd.rc != 1
  changed_when:       false
  become:             true
  
- name: update if firmware update is needed
  shell:              "rpi-eeprom-update -a"
  when:               firmware_check_cmd.rc == 1
  become:             true
  
- name: Set timezone
  timezone:
    name:               "{{ timezone }}"
  become:               true
  
- name: add useful tooling
  apt:
    name:               "{{ useful_tools }}"
    force_apt_get:      yes
  become:               true
  
# reboot if needed
- name: reboot on change
  reboot:
  when:                 reboot_required_file.stat.exists or firmware_check_cmd.rc == 1 or boot_config.changed
  become:               true
  
